site_name: tsigua
repo_url: https://github.com/remexemer/tsigua
site_url: https://remexemer.github.io/tsigua
site_description: Test uv for management.
site_author: Ting-Shuo Hsu
edit_uri: edit/main/docs/
repo_name: remexemer/tsigua
copyright: Maintained by <a href="https://remexemer.com">remexemer</a>.

nav:
  - Home: index.md
  - Modules: modules.md
plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          paths: ["src/tsigua"]
theme:
  name: material
  feature:
    tabs: true
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: white
      accent: deep orange
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: deep orange
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  icon:
    repo: fontawesome/brands/github

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/remexemer/tsigua
    - icon: fontawesome/brands/python
      link: https://pypi.org/project/tsigua

markdown_extensions:
  - toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true
